USE [master]
GO

/****** Object:  Database [PRN211_Exam]    Script Date: 8/23/2023 3:28:49 PM ******/
CREATE DATABASE [PRN211_Exam]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRN211_Exam', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PRN211_Exam.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRN211_Exam_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PRN211_Exam_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRN211_Exam].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PRN211_Exam] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PRN211_Exam] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PRN211_Exam] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PRN211_Exam] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PRN211_Exam] SET ARITHABORT OFF 
GO

ALTER DATABASE [PRN211_Exam] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PRN211_Exam] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PRN211_Exam] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PRN211_Exam] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PRN211_Exam] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PRN211_Exam] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PRN211_Exam] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PRN211_Exam] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PRN211_Exam] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PRN211_Exam] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PRN211_Exam] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PRN211_Exam] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PRN211_Exam] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PRN211_Exam] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PRN211_Exam] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PRN211_Exam] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PRN211_Exam] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PRN211_Exam] SET RECOVERY FULL 
GO

ALTER DATABASE [PRN211_Exam] SET  MULTI_USER 
GO

ALTER DATABASE [PRN211_Exam] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PRN211_Exam] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PRN211_Exam] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PRN211_Exam] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PRN211_Exam] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PRN211_Exam] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PRN211_Exam] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PRN211_Exam] SET  READ_WRITE 
GO

